public with sharing class Day17 {
    /**
     Triggers:
      based some database event some apex code gets invoked and this apex code is called ass trigger


      events:
      1.before insert

      2.after insert

      3.before update
      
      4.after update

      5.before delete
      6.after delete

      7.after udelete


      syntax:
      trigger <triggername> on <objectname> (<events>){
        //code
      }

     
     */
}
