public with sharing class Day19 {
   /** rollup summery trigger 
    * 


    1.create a rollup summery trigger to count number of contacts on account
    assumptions:
    1.one custom field to track number of contacts: Number_of_contacts__c

     i. which object ? contact 
        ii. which context variables? trigger.new ,trigger.oldMAP, trigger.newMAP
        iii. which event ? after insert, after delete, after undelete, after update
        iV. what business logic? inner query 
    */
}
