public  class Day21 {
   /**
    * 
    share table:
    standard object:
    objectnameshare



    custom object :
    objectName__share


    accountShare s= new accountShare();
    s.UserOrGroupId='0055g00000I27fEAAR';
    s.AccountAccessLevel='EDIT';
    s.OpportunityAccessLevel='READ';
    s.CaseAccessLevel   ='READ';
    s.accountID='0015g000015W4elAAC';


    insert s;


    student__Share s1= new student__Share();
    s1.accessLevel='READ';
    s1.parentID='a005g00003BlUGrAAN';
    s1.userOrGroupID='0055g00000I27fEAAR';

    insert s1;

    */
}